- name: setup BaNG database
  include: bangstat_db.yml
  static: no
  when: "'bangdb' in group_names"

- name: get bangstat config
  include: bangstat_config.yml
  static: no
  when: "'bangdb' in group_names or bang_db_support == 1"
