- name: setup BaNG database
  include_tasks: bangstat_db.yml
  when: "'bangdb' in group_names"

- name: get bangstat config
  include_tasks: bangstat_config.yml
  when: "'bangdb' in group_names or bang_db_support == 1"
