- hosts: bang
  vars_files:
    - [ "group_vars/all.yml", "group_vars/all.yml.example" ]
    - [ "group_vars/bangdb.yml", "group_vars/bangdb.yml.example" ]
    - "host_vars/{{ inventory_hostname}}.yml"
  roles:
    - { role: debug,    tags: debug     }
    - { role: bang,     tags: bang      }
    - { role: bangdb,   tags: bangdb    }
  handlers:
    - import_tasks: handlers/services.yml

- hosts: bangweb:bangweb-vagrant
  vars_files:
    - [ "group_vars/all.yml", "group_vars/all.yml.example" ]
    - [ "group_vars/bangweb.yml", "group_vars/bangweb.yml.example" ]
    - "host_vars/{{ inventory_hostname}}.yml"
  roles:
    - { role: bangweb,  tags: bangweb   }
  handlers:
    - import_tasks: handlers/services.yml

- hosts: bangdb
  vars_files:
    - [ "group_vars/all.yml", "group_vars/all.yml.example" ]
    - [ "group_vars/bangdb.yml", "group_vars/bangdb.yml.example" ]
    - "host_vars/{{ inventory_hostname}}.yml"
  roles:
    - { role: bangdb,   tags: bangdb    }
  handlers:
    - import_tasks: handlers/services.yml

- hosts: bangweb-vagrant
  roles:
    - { role: bangweb-vagrant, tags: bangweb-vagrant  }
  handlers:
    - import_tasks: handlers/services.yml
