- name: install apache2 package
  apt: pkg=apache2

- name: install BaNG-Web dependencies
  apt: pkg={{ item }}
  with_items:
    - storman
    - libdancer-perl
    - libdancer-plugin-auth-extensible-perl

- name: copy config.yml.example to config.yml
  copy:
    src: "{{ bang_path }}/config.yml.example"
    dest: "{{ bang_path }}/config.yml"
    remote_src: true
