- name: install apache2 package
  apt: pkg=apache2

- name: install BaNG-Web dependencies
  apt: pkg={{ item }}
  with_items:
    - storman
    - libdancer-perl
    - libdancer-plugin-auth-extensible-perl

- name: copy config.yml.example to config.yml
  copy:
    src: /opt/BaNG/config.yml.example
    dest: /opt/BaNG/config.yml
    remote_src: true
