- name: install apache2 package
  apt: pkg=apache2

- name: check if servername.conf already enabled
  stat: path=/etc/apache2/conf-enabled/servername.conf
  register: apache2_servername_enabled

- name: enable servername.conf
  command: /usr/sbin/a2enconf servername
  when: apache2_servername_enabled == false

- name: install BaNG-Web dependencies
  apt: pkg={{ item }}
  with_items:
    - starman
    - libdancer-perl
    - libdancer-plugin-auth-extensible-perl

- name: Load required Apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - proxy
    - proxy_http

- name: set ServerName
  shell: echo 'ServerName localhost' > /etc/apache2/conf-available/servername.conf
  args:
    creates: /etc/apache2/conf-available/servername.conf

- name: Create apache2_config
  template:
    dest: "{{ bang_config_path }}/apache2_config"
    src: apache2_config.j2

- name: Create symlink to /etc/apache2/sites-available/
  file:
    src: "{{ bang_config_path }}/apache2_config"
    dest: /etc/apache2/sites-available/BaNG.conf
    state: link

- name: check if BaNG.conf already enabled
  stat: path=/etc/apache2/sites-enabled/BaNG.conf
  register: apache2_BaNG

- name: activate BaNG.conf on apache2
  shell: /usr/sbin/a2ensite BaNG
  notify: restart apache2
  when: apache2_BaNG.stat.islnk is not defined

- name: copy config.yml.example to config.yml
  copy:
    src: "{{ bang_path }}/config.yml.example"
    dest: "{{ bang_path }}/config.yml"
    remote_src: true
  when: bang_config_git_repo is not defined

- name: create symlink of etc/config.yml to config.yml
  file:
    src: "{{ bang_config_path }}/config.yml"
    dest: "{{ bang_path }}/config.yml"
    state: link
  when: bang_config_git_repo is defined

- name: check for existing var/log/production.log
  stat: path="{{ bang_path }}/var/log/production.log"
  register: log_available

- name: touch production.log file
  file:
    path: "{{ bang_path }}/var/log/production.log"
    state: touch
    owner: www-data
  when: log_available == false

- name: fix folder ownerships
  file:
    path: "{{ bang_path }}/{{ item }}"
    mode: 0755
    owner: www-data
    state: directory
    recurse: yes
  with_items:
    - "var/log"
    - "var/sessions"

- name: link BaNG-Web.service to /etc/systemd/system/
  file:
    src: "{{ bang_path }}/system/BaNG-Web.service"
    dest: /etc/systemd/system/BaNG-Web.service
    state: link
  notify: restart BaNG-Web service
