- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- import_tasks: tools.yml

- import_tasks: dependencies.yml

- name: clone BaNG git repository
  git:
    repo: "{{ bang_git_repo }}"
    dest: "{{ bang_path }}"
    accept_hostkey: yes
    update: no

- name: get BaNG config
  include_tasks: etc.yml
  when: bang_config_git_repo is defined

- name: get BaNG example config
  include_tasks: etc.example.yml
  when: bang_config_git_repo is not defined

- name: check if BaNG cron file exists
  stat: path=/etc/cron.d/BaNG
  register: bangcron_stat
  check_mode: no

- name: check if BaNG cron file up-to-date
  command: /opt/BaNG/BaNGadm --cron-check
  register: bangadm_result
  when: bangcron_stat.stat.exists
  check_mode: no

- name: create/update BaNG cron file
  shell: /opt/BaNG/BaNGadm --cron-create
  when: bangcron_stat.stat.exists == false or bangadm_result.stdout != ""
