- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- include: tools.yml

- include: dependencies.yml

- name: clone BaNG git repository
  git:
    repo: "{{ bang_git_repo }}"
    dest: "{{ bang_path }}"
    accept_hostkey: yes
    update: no

- name: get BaNG config
  include: etc.yml
  static: no
  when: bang_config_git_repo is defined

- name: get BaNG example config
  include: etc.example.yml
  static: no
  when: bang_config_git_repo is not defined
